name: Pipeline Tests

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]
  schedule:
    - cron: 0 0 * * *

permissions:
  contents: read

jobs:
  flake8:
    strategy:
      matrix:
        os: [ 'ubuntu-latest' ]
        python-version: [ '3.8', '3.9', '3.10', '3.11' ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U flake8 flake8-polyfill robotframework
      - name: Analysing the code with flake8
        run: |
          flake8 $(git ls-files '*.py') --count --show-source --max-complexity=11 --statistics

  pylint:
    strategy:
      matrix:
        os: [ 'ubuntu-latest' ]
        python-version: [ '3.8', '3.9', '3.10', '3.11' ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U setuptools_scm setuptools pylint robotframework pyyaml rpyc
      - name: Analysing the code with pylint
        run: |
          pylint --module-naming-style=any $(git ls-files '*.py')

  robot-framework:
    strategy:
      matrix:
        os: [ 'ubuntu-latest', 'windows-latest' ]
        python-version: [ '3.8', '3.9', '3.10', '3.11' ]
        robotframework-version: [ '5.0.1', '6.0.2', '6.1', '7.0', 'latest' ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
          pip install -U setuptools_scm setuptools
      - name: Install PyYaml
        run: |
          pip install pyyaml
      - name: Install robotframework latest
        if: ${{ matrix.robotframework-version == 'latest' }}
        run: |
          pip install -U robotframework
      - name: Install robotframework ${{ matrix.robotframework-version }}
        if: ${{ matrix.robotframework-version != 'latest' }}
        run: |
          pip install robotframework==${{ matrix.robotframework-version }}
      - name: Install RPyCRobotRemote
        run: |
          pip install -e .
      - name: Executing Robot Framework Tests
        run: |
          python test/server.py 2>&1 &
          sleep 3
          robot test/ 2>&1
